### ISSUE TITLE
[Improvement] Ability to break TDP readings like Randir's VCC efis

### ISSUE THREAD

**Issue by Saren-Arterius** [freecableguy/v3x4#1]
Hi there. Since not every motherboard supports ignoring TDP limit, whatever efi drivers released (including v3x4 here) do not perform as good as [Randir's](https://forums.anandtech.com/threads/what-controls-turbo-core-in-xeons.2496647/page-31#post-38887154). If v3x4 supports breaking TDP reading, that would be very great.

**Comment by freecableguy** [comment]
RC8 includes PowerCut which will disable CPU SVID telemetry and provide for the request feature.  This was broken in RC7 when it was first introduced.  Please see RC8 release page for latest downloads and be sure to reboot following first driver load as may be instructed.  PowerCut requires a reboot to be set following a cold start from shutdown but will survive successive warm reboots.
