### ISSUE TITLE
Help with compiling

### ISSUE THREAD

**Issue by zack4485** [freecableguy/v3x4#10]
All of the instructions seem wrong...

1. The dependency on Cygwin was not noted and I cannot find anything that actually depends on Windows 2003 DDK 3790.1830
2. The instructions say to "install" UDK2015 but I can't find anything to install; does it just need to be downloaded?
3. All of the file paths in the instructions are wrong; for example the edksetup.bat file is not in the basetools directory
4. Even if I move files around and edit batch scripts the build still fails
5. The build command is ignoring the content of target.txt

Can I trouble you to provide a **_LOT_** more detail so that I can build this on my own?

**Comment by oneperfectsunrise** [comment]
The issue I had was with the UDK2015 Release zip which I could only fix by instead downloading the tagged branch of UDK2015 from 'https://github.com/tianocore/edk2/tree/UDK2015' and manually adding the 'BaseTools\Bin\win32' folder from the UDK2015 release zip. At that point you should be able to just follow the instructions from point 3 onwards in the provided README.MD of this repo (assuming you have already done points 1 & 2).
If your still having problems I'd suggest completing step 4 onwards using a developer admin prompt for VS2015.

**Comment by freecableguy** [comment]
Sounds like there may be a type-o or two in my instructions. If someone would please provide me with more detailed instructions for the fix, I am glad to update for all! thanks

**Comment by freecableguy** [comment]
Closing due to no follow-up request and time since request.  Please open a new issue if you still require assistance.
