### ISSUE TITLE
Compile for OS X?

### ISSUE THREAD

**Issue by louisCyphre666** [freecableguy/v3x4#14]
I have a Mac Pro 3,1 with dual quad core Xeons. Is there a way to compile this for Mac?

**Comment by freecableguy** [comment]
EFI is platform agnostic and should work for any UEFI-enabled system regardless of OS.
Although you may need a Windows-based system to compile as-is, the binary has no such dependency.

**Comment by louisCyphre666** [comment]
Thanks. I believe the only issue I'm having is getting all the developer tools for an older version of iOS 6 that I use my DW with. I prefer to use 10.8.5
