### ISSUE TITLE
ASUS Z10PED8-WS

### ISSUE THREAD

**Issue by kahvis** [freecableguy/v3x4#15]
Hi,

I noticed that you are maybe using ASUS Z10PED8-WS motherboard. I am asking tips for regular bios settings for the best performance with this driver. What is best settings for:

**Option / [ in use ]**

CPU1/CPU2 Load-line Calibration [Auto]
CPU1/CPU2 Current Capability [140%]
CPU1/CPU2 Power Phase Control [Optimized]
CPU1/CPU2 Power Thermal Control [140]

Xeon Turbo Charger [Disabled]
CPU1/2 Input Voltage [1.900]

Power Technology [Custom]
Energy Performance Tuning [Disabled]
Config TPD [Disabled]
ACPI T-States [Disabled]

Something else? I just cannot get turbo over 2.8 Ghz on linux. I used to have 3.8 Ghz turbo with Supermicro X10SRA single socket motherboard with same CPU(s).

**Comment by freecableguy** [comment]
Package C3 and/or C6 _MUST_ be enabled for margins required to boost cores.  Since C6 is bugged with v3 Xeons, Disable C6 and _Enable_ C3.

I suspect you do not need 1.900V for Input Voltage.
