### ISSUE TITLE
SVID / General Question

### ISSUE THREAD

**Issue by duketwo** [freecableguy/v3x4#16]
Hey, nice work.

Considering wether I should use this or the payne ffs injection. Are there any benefits over the other?

Especially regarding the SVID - my bios has the setting "SVID Communication = Disable" -- Is this equivalent to ""disable CPU SVID telemetry (a.k.a. "PowerCut")"" ?

Am I right that you can just remove the microcode from the bios, but the OS can later load newer microcode (with meltdown/spectre fixes) without affecting the multi unlock?

Thank you!

**Comment by freecableguy** [comment]
I cannot speak as to the capabilities of the payne FFS injection and so have no comment in that regard.

SVID Communication = Disabled is functionally equivalent to "PowerCut".

You are correct in that microcode can be loaded in Windows at boot time.  A special driver is required.  Search for "VMware CPU Microcode Update Driver"  Whether the microcode you load addresses Meltdown/Spectre will depend on which microcode you make use of.  Personally, I do not protect for these issues as performance is significantly impacted on Haswell.
