### ISSUE TITLE
Turbo freq downgrade

### ISSUE THREAD

**Issue by r3ider** [freecableguy/v3x4#2]
Hi! After applying v3x4-0.10b-i306f2-rc9.efi on xeon e5 2695 v3 (qs) its turbo frequencies has been limited to 3100. Before applying it runned with 3500 mhz. Is it possible to manually set old multiplier 35x in efi or restore default (manufacturer) multiplier?

**Comment by freecableguy** [comment]
Hi.... default configuration for pre-compile builds is to auto limit to max 1C turbo frequency for all-core turbo.  I would recommend checking state of C3, this should be set to ENABLED in BIOS for maximum turbo frequency.  Depending on Microcode, setting C6 to maximum can also provide same affect but can sometime result in unstable behavior and so C3 ENABLED is primary recommendation.  Please let me know if this helps.
