### ISSUE TITLE
8890v3 2.5g i306f3 where do I need to change?

### ISSUE THREAD

**Issue by lingemi** [freecableguy/v3x4#3]
Hello, may I ask 8890v3 2.5g i306f3 where do I need to change?
8890v3 2.4g i306f2 I have a successful Turbo.

**Comment by freecableguy** [comment]
Hi, thanks for contacting.  I have emailed you a special build for CPUID 306F3.  This issue is closed.

**Comment by Zorg33** [comment]
Hi

I am also struggling with quad E7 8890v3 QS (306F3) configuration in a supermicro server.
It seems to use the original turbo mutipliers, no matter what I try.

I compiled the latest code from master branch, everything seems to be fine according to the messages.
I also checked 0x1ad/0x1ae/0x1af and all ratios are 0x21 (33x), but the cpus scale down to 29x above 4 active cores.
I also noticed that Current limiting is active even at x29 multi.

How can I make it work?
Can you please send me your compiled version from above?
thanks!
