### ISSUE TITLE
Missing include file: 'Library/PrePiLib.h'

### ISSUE THREAD

**Issue by sackpower** [freecableguy/v3x4#4]
My UDK2015 build environment on Windows with VS 2015 is working properly. When compiling v3x4.c I get the following error:

> c:\mywork\edk2\MdeModulePkg\v3x4\v3x4.c(4): fatal error C1083: Cannot open include file: 'Library/PrePiLib.h': No such file or directory

Any help is greatly appreciated.

**Comment by freecableguy** [comment]
Easiest way to correct this would be to search for the missing file in overall 'edk2' directory tree and copy into specified directory from script error output.

**Comment by freecableguy** [comment]
Closing for lack of response comment.
