### ISSUE TITLE
Did the Broadwell-E/EP build work?

### ISSUE THREAD

**Issue by miyconst** [freecableguy/v3x4#6]
Hi. I am curious to know if the experimental [`RC9`](https://github.com/freecableguy/v3x4/releases/tag/v3x4-0.10b-i406f1-rc9) release worked to unlock turbo frequency on all cores with Xeon E5 V4 CPUs.

**Comment by rmaenk** [comment]
Only V3 is supported, as I know. V3 processors have a bug that is used to enable unlock turbo frequency on all cores. About V4 - this bug was fixed by Intel - may be some one will find another way, but now there is no such information.
Regards, 
Roman

**Comment by miyconst** [comment]
@rmaenk, thank you for the quick answer.

**Comment by freecableguy** [comment]
I have personally verified this does not work for v4 Xeon in _dual_ configuration.

**Comment by mmkhmmkh** [comment]
> I have personally verified this does not work for v4 Xeon in _dual_ configuration.

Hi :)
What about single configuration? (2697 but single slot).

**Comment by rmaenk** [comment]
Hi @mmkhmmkh,
E5 2600 V4 processors do not support turboboost unlock in any configurations: single, dual or quad.
