### ISSUE TITLE
FFS. Not work with dual cpus motherboards

### ISSUE THREAD

**Issue by mxp100** [freecableguy/v3x4#7]
Tested on Asus Z10pa-d8, efi driver work correctly and FFS driver not worked, if patch cpu with 1 cpu as FFS, unlock work with one CPU

**Comment by mxp100** [comment]
if convert to FFI driver and add as last in DXE drivers, not work correctly may be cpu infos used in code, not correct in DXE loading step?

**Comment by freecableguy** [comment]
Hi mxp100, you are not the first to publicly comment that dual-CPU systems are *not* compatible with FFS solution. My recommendation would be to make use of the driver as-compiled without embedding for flashing.
