### ISSUE TITLE
❓ Is it possible to compile v3x4 driver into PEI?

### ISSUE THREAD

**Issue by miyconst** [freecableguy/v3x4#9]
The current implementation is available in two forms:

- `EFI` driver, it can be installed on the OS level.
-  `DXE` driver, it can be injected into the BIOS itself.

The problem with the `DXE` driver is that this section is not loaded when the PC goes live from the sleep mode.

Would it be possible to produce a `PEI` driver, which can be injected into the BIOS section, which is executed upon wake up?

P.S. I apologize if this is a stupid question and the answer is obvious.

**Comment by freecableguy** [comment]
The following link should allow for conversion of DXE to FFS format for direct injection into BIOS. I am reliably informed this method is incompatible with dual CPU systems but does work for single CPU systems.

Perhaps do some investigating for us and report back what you learn.

https://github.com/pbatard/efifs/wiki/Adding-a-driver-to-a-UEFI-firmware

**Comment by freecableguy** [comment]
Lol. Is this your site?:
http://www.miyconst.com/Blog/View/2081/xeon-e5-2600-v3-turbo-boost-unlock

**Comment by miyconst** [comment]
Yes, that's my website 😄.

In short:

- There is already a way to create a `DXE` driver and inject it into the BIOS.
- **I am looking for a way to create a `PEI` driver, which is injected into another BIOS region.**

The `DXE` drivers are not executed when resuming from the sleep mode, that's why applying such hack effectively disables the sleep mode.

**Comment by Cclown98** [comment]
@miyconst we are actually on the same boat, i've been trying to find the way to create a PEI driver since the turbo dies when the board resumes from sleep on both os x and windows

**Comment by mxp100** [comment]
needed service listeners for wake up for reinitialize hacks
https://www.uefi.org/sites/default/files/resources/PI_Spec_1_6.pdf
may be help this docs....

**Comment by miyconst** [comment]
It seems to be done by a user called `ser8989` - [АНЛОК (Андервольтинг) турбобуста процессора
Unlock turbo boost (Undervolting)](https://forums.overclockers.ru/viewtopic.php?p=16981941#p16981941).

**Comment by freecableguy** [comment]
PEI embedding:
https://forums.anandtech.com/threads/what-controls-turbo-core-in-xeons.2496647/post-40316855

**Comment by freecableguy** [comment]
Specific targets for more information on PEI imbedding:

https://forums.overclockers.ru/viewtopic.php?p=17089770#p17089770
https://forums.overclockers.ru/viewtopic.php?p=17092454#p17092454

**Comment by miyconst** [comment]
Following [this guide](https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/) I was able to successfully implement PEI embedding into a Machinist X99Z / X99-K9 BIOS. The BIOS is available in the [Mi899](https://github.com/miyconst/Mi899) tool.

Closing the issue as the PEI embedding solution is available and tested.
